### ISSUE TITLE
BUG: ncappzoo continue to set error saying setup environmental variable using setupvars.sh although it is already set

### ISSUE THREAD

**Issue by krishkar2019** [movidius/ncappzoo#350]
I am using raspberry PI and ncappzoo and make run gives error as follows:
root@raspberrypi:/home/pi/ncappzoo/networks/ssd_inception_v2_food# source /opt/intel/openvino/bin/setupvars.sh
[setupvars.sh] OpenVINO environment initialized
root@raspberrypi:/home/pi/ncappzoo/networks/ssd_inception_v2_food# make run_py
Makefile:512: warning: overriding recipe for target 'uninstall-reqs'
Makefile:228: warning: ignoring old recipe for target 'uninstall-reqs'

SSD Inception V2 Food: Downloading model files...
model file tensorflow_model/ssd_inception_v2_coco.config already exists, skipping download
model file tensorflow_model/frozen_inference_graph.pb already exists, skipping download

SSD Inception V2 Food: Making dependencies... 
Intel OpenVINO environment is already set!

SSD Inception V2 Food: Downloading required data...
test file test_images/test1.JPG already exists, skipping download
test file test_images/test2.JPG already exists, skipping download
test file test_images/test3.JPG already exists, skipping download
license file test_images/license.txt already exists, skipping download
mo.py path is already set!

SSD Inception V2 Food: Compiling model to IR...
Compiling FP32 model...
mkdir: cannot create directory ‘ssd_inception_v2_mo_fp32’: File exists
/bin/sh: 7: mo.py: not found
**Make sure to set the OpenVINO environment variables using the setupvars.sh script found in <your OpenVINO install location>/bin/ folder.**
make: *** [Makefile:162: compile_model] Error 1
root@raspberrypi:/home/pi/ncappzoo/networks/ssd_inception_v2_food#

**Comment by DrewBearly** [comment]
If you're using the OpenVINO runtime for Raspbian, then this is actually **expected behaviour**. 

The runtime does not include the model optimizer - since the checks for the OpenVINO environment variables also expect the model optimizer (mo.py) and fail to find it, it responds with that error message. If you want to run the _ncappzoo_ on raspberry pi, follow the directions in the README.md to clone the open source version of openvino and add the model optimizer paths to your shell's PATH and PYTHONPATH, or see the open source's OpenVINO documentation for more details: [GitHub](https://github.com/opencv/dldt)
